export const studioLogosList = [
    '2D-DUB',
    '2x2',
    '3df voice',
    'Akame',
    'Akari',
    'Amazing Dubbing',
    'Amber',
    'Ancord',
    'AniBaza',
    'AniBoom',
    'AniBreeze-s',
    'AniBreeze',
    'AniClub',
    'AniCosmic',
    'AniDUB',
    'AniFame',
    'AniFilm',
    'AniJoy',
    'AniLane',
    'AniLeague',
    'AniLiberty (AniLibria)',
    'AniLibria-s',
    'AniLibria',
    'AniMaunt',
    'Animedia',
    'AnimeJet',
    'animereactor',
    'AnimeVost',
    'AniMovie',
    'Animy-s',
    'Animy',
    'AniNya',
    'AniPLague',
    'AniPlay Studio',
    'Aniraccoon',
    'AniRai',
    'AniRise-s',
    'AniRise',
    'AniStar',
    'Anton Shanteau',
    'Anything Group',
    'ArrowHell',
    'Brees Club',
    'CelestialDub',
    'ColdFilm',
    'ConeVoice',
    'Crunchyroll-s',
    'Crunchyroll',
    'DejzDub',
    'DM Project',
    'DOBROVOICE',
    'Dream Cast',
    'DubClub',
    'EVA',
    'Flarrow Films',
    'Freedub Studio',
    'FSG Sanae-s',
    'FSG Sanae',
    'FumoDub',
    'Get Smart Group',
    'GoLTFilm',
    'GrandStudio',
    'HaronMedia',
    'HDrezka Studio',
    'Head Pack Films',
    'HORIZON',
    'IIITUKATUPKA',
    'Inari Studio',
    'Indie Dub',
    'INSOMNIA',
    'J&N Union',
    'JAM',
    'Jisedai',
    'Kalabs Studio',
    'KANSAI Studio',
    'Kazoku-s',
    'Kazoku',
    'KoeKak',
    'LampStudio',
    'LDA TEAM',
    'LE-Production',
    'LightFamily-s',
    'LightFamily',
    'MC Entertainment',
    'MedusaSub-s',
    'MedusaSub',
    'MifFan',
    'MoonWalkers',
    'NekoVoice',
    'Netflix-s',
    'Netflix',
    'NewComers',
    'OBELISK Project',
    'Omori',
    'onibaku',
    'OnWave',
    'OpenDub',
    'persona99',
    'Reanimedia',
    'Risens Team',
    'Saturn Union',
    'SEKAI PROJECT',
    'ShadowVoice',
    'Shikoku Studio',
    'Shiroi Kitsune',
    'SHIZA Project',
    'SillyCat',
    'Silver AniAge',
    'SovetRomantica-s',
    'SovetRomantica',
    'STEPonee',
    'Studio Band',
    'SubVost-s',
    'SubVost',
    'TAKEOVER Project',
    'TVShows',
    'VF-Studio',
    'VoiceHub',
    'VoiceLand',
    'Wakanim-s',
    'Wakanim',
    'Xala.Project',
    'YakuSub-s',
    'YakuSub',
    'Youkai Studio',
    'youmiteru',
    'Вистерия',
    'Кладбище топовых релизов',
    'КОМНАТА ДИДИ',
    'Невинный Кружок',
    'ОВН',
    'Оканэ',
    'ПВА ШОУ',
    'РуАниме  DEEP-s',
    'РуАниме  DEEP',
    'СВ-Дубль',
    'Творческая студия МИР',
    'Ушастая озвучка-s',
    'Ушастая озвучка',
    '!Subs',
]