name: Master Checks (and Deploy)

on:
  workflow_dispatch:
  push:
    branches: [ "master" ]

permissions:
  contents: read
  pull-requests: read

jobs:
  prerelease-checks:
    name: Prerelease Checks
    uses: ./.github/workflows/shared-prerelease-checks.yml
    with:
      force: ${{ github.event_name == 'workflow_dispatch' }}

  deploy:
    name: Deploy
    environment: production
    runs-on: ubuntu-latest
    timeout-minutes: 3
    needs: prerelease-checks
    if: ${{ needs.prerelease-checks.outputs.code-changed == 'true' }}

    permissions:
      id-token: write
      contents: write

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: 'true'

      - name: Bump version and push tag
        id: tag
        uses: step-security/github-tag-action@9c71d71802cca8038be2220876265db07000b404 # v6.2.1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""
          default_bump: patch

      - uses: pnpm/action-setup@0ebf47130e4866e96fce0953f49152a61190b271 # v6.0.9

      - uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile --filter infra...

      - name: Generate Telegram texts
        run: pnpm run textgen

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@cbe3b392738ccf3f987d68400dafcf4b0624a56c # v6
        with:
          role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_PROD }}:role/github-actions-cdk-deploy-north-1
          aws-region: eu-north-1

      - name: Perform release
        run: pnpm run cdk:deploy --require-approval broadening
